---
title: "Station_Map"
author: "Jose Martinez"
date: "2023-03-26"
output: html_document
---

```{r setup, include=FALSE}
########load required libraries
library(tidyverse)
library(plotly)
library(patchwork)
library(Hmisc)
library(maps)
library(rstudioapi)
library(ggmap)
library(ggrepel)
library(tmaptools)
```


```{r}
df = data.frame(lon = c(-66.773, -66.763, -66.732, -66.732),
            lat = c(17.990, 17.976, 17.980, 17.957),
            Station = c(1,2,3,4),
            Depth = c(13.5296,14.0382,13.5154,13.6916))

df_depth = data.frame(Station = c(1,2,3,4), Depth = c(13.5296,14.0382,13.5154,13.6916))
```


```{r}
# Draw the map
register_google(key = "AIzaSyDiR6zaf6-zLW35sH_XftY5XkVRqrSuq90")

studymap1 = ggmap(get_googlemap(center = c(lon = -66.770713 , lat = 17.983142), 
                            zoom = 13,
                            maptype = 'satellite',
                            color = 'color',
                            scale = 2,
                            label = Depth))

# Add the points
studymap1 = studymap1 + 
  geom_point(data = df, aes(x = lon, y = lat, color = as.factor(Station)), 
      alpha = 0.6,  size = 5)+
  labs(color='Stations')+
  #geom_text(label = df$Depth,hjust = 1,vjust = 1)+
  ylab("Latitude (°N)")+
  xlab("Longitude (°E)")+
  ggtitle("Possible Project Stations Map")+
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_blank(),
        text = element_text(size = 12),
        legend.position= "right",
        plot.title = element_text(vjust = 2, hjust = 0.5, size = 15))

print(studymap1)

ggsave("Possible_StationMap.pdf",studymap1,width =16, height = 8)



#depth_t = write.table(df_depth,row.names = FALSE)

```




```{r}
register_google(key = "AIzaSyDiR6zaf6-zLW35sH_XftY5XkVRqrSuq90")

studymap = ggmap(get_googlemap(center = c(lon = -66.770713 , lat = 17.983142), 
                            zoom = 13,
                            maptype = 'satellite',
                            color = 'color',
                            scale = 2,))
                    
print(studymap)+
  #ggplot()+
  #geom_point(aes(x = -66.793359, y = 17.98575,size = Station),shape = 15,size = 5,color = 'purple')+ # Callo Maria Langa
  #geom_point(shape = 16, aes(x= -66.749231, y = 17.965728),size = 5,color = 'purple')+  # left most station (muddy)
  geom_point(shape = 13,aes(x = -66.773, y = 17.990),size = 5,color = 'red')+ # inshore north
  geom_point(shape = 13,aes(x = -66.763, y = 17.976),size = 5,color = 'red')+ # inshore south
  geom_point(shape = 13,aes(x = -66.732, y = 17.980),size = 5,color = 'red')+ # offshore north
  geom_point(shape = 13,aes(x = -66.732, y = 17.957),size = 5,color = 'red')+ # offshore south
  ylab("Latitude (N)")+
  xlab("Longitude (E)")+
  ggtitle("Possible Project Station Map")+
  scale_fill_discrete(name = "Site")+
  scale_color_discrete(name = "Site")+
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_blank(),
        text = element_text(size = 12),
        legend.position= "top",
        plot.title = element_text(hjust = 0.5, size = 15))
```


17.966273, -66.770818












